### ISSUE TITLE
Usability Suggestions

### ISSUE THREAD

**Issue by jsteinich** [borisdj/CsCodeGenerator#2]
- `UsingDirectives` shouldn't require `using `, just add it when writing
- `Namespace` shouldn't require `namespace`, just add it when writing
- Switch dictionaries to lists for fields, properties, methods, etc. A dictionary doesn't necessarily maintain ordering and requires slightly more code to use. There are other ways to enforce unique names.
- Remove `Console.ReadKey()` in `CsGenerator`. That isn't an expected behavior.
- Don't use `Console.WriteLine` and instead use a logging framework, i.e. `Microsoft.Extensions.Logging`
- Improve nested class indenting. Having to manually adjust the indent isn't fun and is unexpected.

**Comment by borisdj** [comment]
All done except Nested class indenting.
This I have to figure what is the best way to integrate into current logic.
Implementation should be shared with setting Indent on Method writing.
