### ISSUE TITLE
Version 1.0.2 Prints out "Press any key to close."

### ISSUE THREAD

**Issue by michaelvannevel** [borisdj/CsCodeGenerator#5]
Using Visual Studio 2019.  I do not see it in the code base currently, so a bit confused where its coming from, but each time directly after CsGenerator.CreateFiles() the breakpoint does not move on to the next line, and then displays "Press any key to close.".  

Not sure if you're seeing the same issue when using the nuget package or not.  Otherwise, loving the library so far, and code looks  nice and clean.

**Comment by borisdj** [comment]
Not sure about that Text.
Anyway I've just published new Nuget since code had some changes that were not published so try that first.
And secondly you could load the source into the project and debug it directly.
