### ISSUE TITLE
Comment missing <summary></summary>

### ISSUE THREAD

**Issue by IvanJosipovic** [borisdj/CsCodeGenerator#6]
Zdravo

Currently Comment renders the following:
```
    // my comment
    public class MyClass 
```
I would like Comment to render the following:
```
    /// <summary>
    /// my comment
    /// </summary>
    public class MyClass
```

This will allow the generated code to output [XML Documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/)

**Comment by borisdj** [comment]
Pozdrav,

Will try to add it.

**Comment by borisdj** [comment]
Added
