### ISSUE TITLE
Fluent interface

### ISSUE THREAD

**Issue by robinmayr** [borisdj/CsCodeGenerator#9]
Hi, 
Lovely project this. I saw the example on the main page and it is my impression that writing a class could benefit greatly from fluent interfaces. So, a class generator could be written something like this:

```c#
var code = Class
  .WithName("foo")
  .WithComment("example class")
  .WhichImplements("object")
  .WithProperty("Value", "get")
  .WithMethod("methodname", int, 
    m => m.WithComment("a method comment")
      .WithImplementation("// do nothing"))
``` 
I think this could be neat, and possibly done with extension methods in a way that does not intrude with the current working of the project. Do you guys happen to agree?

**Comment by borisdj** [comment]
There was a similar question @jsteinich from long time  ago https://github.com/borisdj/CsCodeGenerator/issues/3
Have managed to add it now.
In ReadMe is added Fluent example and new Nuget published 2.0.3

PS
Fluent calls are composed with BaseElement, when configuring deeper level we need to instanciate with New and call in that scope, which can be seen from the code sample.
If one would want to be able to get subElements returned to main scope then more extension methods would need to be added into the library, there is commented one method in source code for this case: `WithPropertyReturn`
